In [1]:
# 사칙연산

In [2]:
import numpy as np

In [3]:
x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
x+x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [5]:
x-x

array([[0, 0, 0],
       [0, 0, 0]])

In [6]:
x/x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
x*x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [8]:
x**x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [9]:
# 배열간의 곱셈
# 벡터의 내적 : 두 배열간의 곱셈
# 두개의 행렬에서 첫번째 행렬의 열 크기와 두 번째 행렬의 행 크기가 동일해야 함
# m x n   n x i   내적연산을 하면 m x i
# ( m x n ) . ( n x i )
# 1 2  5 6  1*5+2*7  1*6+2*8
# 3 4  7 8  3*5+4*7  3*6+4*8

In [10]:
x_1 = np.arange(1,7).reshape(2,3)
x_2 = np.arange(1,7).reshape(3,2)
x_1, x_2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [12]:
x_1.shape, x_2.shape

((2, 3), (3, 2))

In [13]:
x_1.dot(x_2)

array([[22, 28],
       [49, 64]])

In [14]:
# 브로드 캐스팅 연산
#  행렬과 스칼라 값들간의 연산이나 행렬과 벡터간의 연산

In [15]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
x+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [17]:
x-2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [18]:
x // 2

array([[0, 1, 1],
       [2, 2, 3],
       [3, 4, 4]], dtype=int32)

In [19]:
x**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [20]:
# 행렬과 스칼라가 아닌 그외 연산들..

In [21]:
x = np.arange(1,13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
v = np.arange(10,40,10)
v

array([10, 20, 30])

In [23]:
x+v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [26]:
# 넘파이 성능 측정
def sclar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar*value)
    return result
iternation_max = 10000
vector = list(range(iternation_max))
scalar = 2

In [27]:
# for문을 이용한 성능
%timeit sclar_vector_product(scalar, vector)

728 µs ± 47.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [28]:
# 리스트 컴프리핸션
%timeit [scalar*value for value in range(iternation_max) ]

541 µs ± 37.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [29]:
# 넘파이를 이용한 성능측정
%timeit np.arange(iternation_max)*scalar

13.7 µs ± 205 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [30]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x > 4

array([False, False, False, False,  True,  True,  True,  True,  True])

In [32]:
x = np.array([1,3,0])
y = np.array([2,1,7])
x > y

array([False,  True, False])

In [33]:
# 비교  연산 함수
# all , any
# 배열내부의 값중에 모든 값이 true 가되어야 true
# any 배열내부의 값중에 하나라도 true이면 true

In [34]:
(x > y).all()

False

In [35]:
(x > y).any()

True

In [37]:
# where 함수 : 배열에서 찾은 값에 인덱스를 반환
x = np.array([4,6,7,3,2])
x>5

array([False,  True,  True, False, False])

In [38]:
np.where(x > 5)

(array([1, 2], dtype=int64),)

In [39]:
np.where(x > 5, 10,20)

array([20, 10, 10, 20, 20])

In [40]:
# argsort - sort index
# argmax -  max index
# argmin - min index

In [41]:
x = np.array([4,6,7,3,2])
np.argsort(x)

array([4, 3, 0, 1, 2], dtype=int64)

In [42]:
np.argmax(x)

2

In [43]:
np.argmin(x)

4

In [44]:
from random import sample

In [52]:
x = np.array( sample(range(1,100),10))
x

array([61, 15, 79, 58, 74, 30, 91, 52, 33, 28])

In [54]:
cond = x > 50
cond

array([ True, False,  True,  True,  True, False,  True,  True, False,
       False])

In [55]:
x[cond]

array([61, 79, 58, 74, 91, 52])

In [56]:
type(x)

numpy.ndarray

In [57]:
x.shape

(10,)

In [58]:
# fancy index : 정수형 배열의 값을 사용하여 해당 정수의 인덱스에 위치한 값을 반환
# 정수로만 구성

In [59]:
x = np.array([4,6,7,3,2])
cond = np.array([1,2,0,2,2,2],int)
x, cond

(array([4, 6, 7, 3, 2]), array([1, 2, 0, 2, 2, 2]))

In [60]:
x[cond]

array([6, 7, 4, 7, 7, 7])

In [61]:
x.take(cond)

array([6, 7, 4, 7, 7, 7])

In [62]:
x = np.array([[1,4],[9,16]],int)
a = np.array([0,1,1,1,0,0],int)
b = np.array([0,0,0,1,1,1],int)
x,a,b

(array([[ 1,  4],
        [ 9, 16]]),
 array([0, 1, 1, 1, 0, 0]),
 array([0, 0, 0, 1, 1, 1]))

In [63]:
x[a,b]

array([ 1,  9,  9, 16,  4,  4])