## 케라스 모델을 만드는 방법

In [2]:
# Sequential 클래스
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(64,activation='relu'),
    layers.Dense(10,activation='softmax'),
])

In [11]:
# 점진적으로 Sequenential 모델 만들기
model = keras.Sequential()
model.add(layers.Dense(10,activation='relu'))
model.add(layers.Dense(10,activation='softmax'))

# 가중치를 만들기위해 모델을 호출

In [13]:
import numpy as np
model.build(input_shape=(None,3))

In [14]:
model.weights

[<tf.Variable 'dense_4/kernel:0' shape=(3, 10) dtype=float32, numpy=
 array([[ 0.65858877, -0.57797194,  0.41845393,  0.4902631 , -0.19472605,
          0.6434659 , -0.6606332 , -0.15222257, -0.5996388 ,  0.39405823],
        [-0.6489726 , -0.09328169, -0.5287276 , -0.43231142, -0.65720725,
          0.51808226,  0.20914036,  0.25468862, -0.52722466, -0.5128592 ],
        [ 0.0816353 , -0.49643606,  0.60862255,  0.30925995,  0.55039   ,
          0.2997296 ,  0.03254402, -0.11580104,  0.18438011,  0.19523996]],
       dtype=float32)>,
 <tf.Variable 'dense_4/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_5/kernel:0' shape=(10, 10) dtype=float32, numpy=
 array([[ 0.539994  ,  0.24339867,  0.19437599, -0.5031097 , -0.4557228 ,
         -0.19302961,  0.2560475 ,  0.4392038 ,  0.39331698, -0.09758469],
        [ 0.4964168 ,  0.24111158, -0.04845935, -0.12723494,  0.4446745 ,
          0.43546015, -0.14564592, -0

In [15]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 10)                40        
                                                                 
 dense_5 (Dense)             (None, 10)                110       
                                                                 
Total params: 150
Trainable params: 150
Non-trainable params: 0
_________________________________________________________________


In [16]:
model = keras.Sequential(name='myModel')
model.add(layers.Dense(64,activation='relu', name='first_layer'))
model.add(layers.Dense(10,activation='relu', name='last_layer'))
model.build((None,3))
model.summary()

Model: "myModel"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 first_layer (Dense)         (None, 64)                256       
                                                                 
 last_layer (Dense)          (None, 10)                650       
                                                                 
Total params: 906
Trainable params: 906
Non-trainable params: 0
_________________________________________________________________


In [17]:
# 모델의 입력 크기를 미리 지정
model = keras.Sequential()
model.add(keras.Input(shape=(3,)))
model.add(layers.Dense(64,activation='relu'))
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 64)                256       
                                                                 
Total params: 256
Trainable params: 256
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.add(layers.Dense(10,activation='softmax'))
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 64)                256       
                                                                 
 dense_7 (Dense)             (None, 10)                650       
                                                                 
Total params: 906
Trainable params: 906
Non-trainable params: 0
_________________________________________________________________


# 함수형 API
# 두개의 Dense층을 가지는 간단한 함수형 모델

In [26]:
inputs = keras.Input(shape=(3,), name='my_input')
features = layers.Dense(64,activation='relu')(inputs)
outputs = layers.Dense(10,activation='softmax')(features)

In [28]:
model = keras.Model(inputs=inputs, outputs=features)
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 my_input (InputLayer)       [(None, 3)]               0         
                                                                 
 dense_9 (Dense)             (None, 64)                256       
                                                                 
Total params: 256
Trainable params: 256
Non-trainable params: 0
_________________________________________________________________


In [29]:
model = keras.Model(inputs=inputs, outputs=outputs)
model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 my_input (InputLayer)       [(None, 3)]               0         
                                                                 
 dense_9 (Dense)             (None, 64)                256       
                                                                 
 dense_10 (Dense)            (None, 10)                650       
                                                                 
Total params: 906
Trainable params: 906
Non-trainable params: 0
_________________________________________________________________


# 다중입력, 다중 출력 함수형 모델

In [30]:
vocabulary_size = 10000
num_tags = 100
num_departments = 4

In [31]:
title = keras.Input(shape=(vocabulary_size,),name='title')
text_body = keras.Input(shape=(vocabulary_size,), name='text_body')
tags = keras.Input(shape=(num_tags,), name='tags')

In [33]:
features =  layers.Concatenate()([title,text_body,tags])
features =  layers.Dense(64,activation='relu')(features)
priority = layers.Dense(1,activation='sigmoid',name='priority')(features)
department =  layers.Dense(num_departments,activation='softmax',name='department')(features)
model = keras.Model(inputs=[title,text_body,tags], outputs = [priority,department])

In [38]:
model.summary()

Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 title (InputLayer)             [(None, 10000)]      0           []                               
                                                                                                  
 text_body (InputLayer)         [(None, 10000)]      0           []                               
                                                                                                  
 tags (InputLayer)              [(None, 100)]        0           []                               
                                                                                                  
 concatenate (Concatenate)      (None, 20100)        0           ['title[0][0]',                  
                                                                  'text_body[0][0]',        

# 입력과 타깃 배열 리스트를 전달해서 모델 훈련

In [41]:
import numpy as np
num_samples = 1280
title_data = np.random.randint(0,2, size=(num_samples, vocabulary_size))
text_body = np.random.randint(0,2, size=(num_samples, vocabulary_size))
tags_data = np.random.randint(0,2,size=(num_samples,num_tags))

In [42]:
priority_data = np.random.random(size=(num_samples,1))
department_data = np.random.randint(0,2,size=(num_samples, num_departments))

In [43]:
model.compile(optimizer='adam',loss = ['mse','categorical_crossentropy'],metrics=['mae','acc'])

In [45]:
history = model.fit([title_data,text_body, tags_data],[priority_data,department_data],epochs=1)

40/40 [==============================] - 1s 14ms/step - loss: 16.1834 - priority_loss: 0.3153 - department_loss: 15.8681 - priority_mae: 0.4813 - priority_acc: 0.0000e+00 - department_mae: 0.5044 - department_acc: 0.2805


In [46]:
model.evaluate([title_data,text_body, tags_data],[priority_data,department_data])

40/40 [==============================] - 0s 6ms/step - loss: 5.3147 - priority_loss: 0.3217 - department_loss: 4.9930 - priority_mae: 0.4880 - priority_acc: 0.0000e+00 - department_mae: 0.4727 - department_acc: 0.1562


[5.31471586227417,
 0.32170844078063965,
 4.993007659912109,
 0.4879694879055023,
 0.0,
 0.47270798683166504,
 0.15625]

In [48]:
priority_preds, department_preds = model.predict([title_data, text_body, tags_data])

40/40 [==============================] - 0s 6ms/step


In [49]:
priority_preds, department_preds

(array([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]], dtype=float32),
 array([[2.5395232e-01, 2.4678588e-01, 8.3189848e-04, 4.9842989e-01],
        [2.1257801e-01, 2.1136189e-01, 9.2253287e-04, 5.7513762e-01],
        [2.8535211e-01, 1.4953715e-01, 3.5004059e-04, 5.6476074e-01],
        ...,
        [1.6822629e-01, 3.2191801e-01, 1.2392204e-03, 5.0861651e-01],
        [1.3404514e-01, 1.7240125e-01, 8.2896464e-04, 6.9272470e-01],
        [2.9021379e-01, 3.4761614e-01, 1.2575313e-03, 3.6091247e-01]],
       dtype=float32))