In [28]:
!pip install torch

In [2]:
import torch
import numpy as np
torch.manual_seed(1234)

In [29]:
from torch import Tensor

# 텐서
    스칼라는 하나의 숫자
    벡터는 배열
    행렬은 숫자의 2-D 배열
    텐서는 숫자의 N-D 배열

In [26]:
torch.__version__

'1.13.0+cpu'

In [9]:
# 5행 3열 텐서
def describe(x):
    print(f"타입:{x.type()}")
    print(f"크기:{x.shape}")
    print(f"값:{x}")

module

In [10]:
describe(torch.Tensor(2,3))

타입:torch.FloatTensor
크기:torch.Size([2, 3])
값:tensor([[-7.0393e-18,  7.4829e-43, -7.0394e-18],
        [ 7.4829e-43, -7.0394e-18,  7.4829e-43]])


In [11]:
describe(torch.randn(2,3))

타입:torch.FloatTensor
크기:torch.Size([2, 3])
값:tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


In [12]:
describe(torch.rand(2,3))

타입:torch.FloatTensor
크기:torch.Size([2, 3])
값:tensor([[0.7749, 0.8208, 0.2793],
        [0.6817, 0.2837, 0.6567]])


In [13]:
# 1이나 0으로 채워진 텐서
describe(torch.zeros(2,3))

타입:torch.FloatTensor
크기:torch.Size([2, 3])
값:tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [14]:
x = torch.ones(2,3)
describe(x)

타입:torch.FloatTensor
크기:torch.Size([2, 3])
값:tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [16]:
# 파이토치에서 _가 붙은 연산은 inplace=True
describe(x.fill_(5))

타입:torch.FloatTensor
크기:torch.Size([2, 3])
값:tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [17]:
describe(x)

타입:torch.FloatTensor
크기:torch.Size([2, 3])
값:tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [19]:
# 리스트로도 만들수 있음
x = torch.Tensor([
    [1,2],
    [2,4]
])
describe(x)

타입:torch.FloatTensor
크기:torch.Size([2, 2])
값:tensor([[1., 2.],
        [2., 4.]])


In [22]:
# 넘파일 배열로도 만들수 있음
npy = np.random.rand(2,3)
print(npy)
describe(torch.Tensor(npy))

[[0.59930047 0.29121709 0.7573667 ]
 [0.57039852 0.6372994  0.22570842]]
타입:torch.FloatTensor
크기:torch.Size([2, 3])
값:tensor([[0.5993, 0.2912, 0.7574],
        [0.5704, 0.6373, 0.2257]])


In [25]:
# 텐서 타입
x = torch.arange(6).view(2,3)
describe(x)

타입:torch.LongTensor
크기:torch.Size([2, 3])
값:tensor([[0, 1, 2],
        [3, 4, 5]])


In [33]:
x = torch.FloatTensor([
    [1,2,3],
    [4,5,6]
]
)
x = x.long()
describe(x)

타입:torch.LongTensor
크기:torch.Size([2, 3])
값:tensor([[1, 2, 3],
        [4, 5, 6]])


In [41]:
x = torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ],
    dtype = torch.int64
)
describe(x)

타입:torch.LongTensor
크기:torch.Size([2, 3])
값:tensor([[1, 2, 3],
        [4, 5, 6]])


In [42]:
x = x.float()
describe(x)

타입:torch.FloatTensor
크기:torch.Size([2, 3])
값:tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [44]:
x = torch.randn(2,3)
x

tensor([[-0.4175,  0.7618,  0.5356],
        [ 1.5739, -0.4864, -0.6622]])

In [45]:
describe(torch.add(x,x))

타입:torch.FloatTensor
크기:torch.Size([2, 3])
값:tensor([[-0.8351,  1.5236,  1.0713],
        [ 3.1477, -0.9729, -1.3244]])


In [46]:
describe(x+x)

타입:torch.FloatTensor
크기:torch.Size([2, 3])
값:tensor([[-0.8351,  1.5236,  1.0713],
        [ 3.1477, -0.9729, -1.3244]])


In [48]:
x = torch.arange(6)
x

tensor([0, 1, 2, 3, 4, 5])

In [57]:
x = x.view(2,3)
describe(x)

타입:torch.LongTensor
크기:torch.Size([2, 3])
값:tensor([[0, 1, 2],
        [3, 4, 5]])


In [70]:
describe(torch.transpose(x,0,1))
describe(x.T)

타입:torch.LongTensor
크기:torch.Size([3, 2])
값:tensor([[0, 3],
        [1, 4],
        [2, 5]])
타입:torch.LongTensor
크기:torch.Size([3, 2])
값:tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [59]:
describe(torch.sum(x,axis = 0))
describe(torch.sum(x,dim = 0))

타입:torch.LongTensor
크기:torch.Size([3])
값:tensor([3, 5, 7])


In [60]:
describe(torch.sum(x,axis = 1))
describe(torch.sum(x,dim = 1))

타입:torch.LongTensor
크기:torch.Size([2])
값:tensor([ 3, 12])
타입:torch.LongTensor
크기:torch.Size([2])
값:tensor([ 3, 12])


In [74]:
# 슬라이싱 제공
x = torch.arange(6).view(2,3)
describe(x)
describe(x[:1,:2])

타입:torch.LongTensor
크기:torch.Size([2, 3])
값:tensor([[0, 1, 2],
        [3, 4, 5]])
타입:torch.LongTensor
크기:torch.Size([1, 2])
값:tensor([[0, 1]])


In [77]:
inx = torch.LongTensor([0,2])
describe(torch.index_select(x,dim=1,index = inx))

타입:torch.LongTensor
크기:torch.Size([2, 2])
값:tensor([[0, 2],
        [3, 5]])


In [80]:
# 숫자가 증가되는 벡터를 만들수 있음
x = torch.arange(0,20)
describe(x)

타입:torch.LongTensor
크기:torch.Size([20])
값:tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])


In [81]:
# view - >텐서의 차원을 변경
print(x.view(1,20))

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19]])


In [82]:
print(x.view(1,-1))

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19]])


In [88]:
print(x.view(4,-1))

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
