## 넘파이
### 과학 계산용 라이브버리
### 벡터나 행렬 같은 선형대수 표현법을 코드로 처리
### 다차원 리스트나 크기가 큰 데이터 처리에 유리

In [3]:
import numpy as np

In [ ]:
넘파이 배열(ndarray) : 넘파이에서 텐서 데이터를 다루는 객체
텐서(tensor):선형대수에서 데이터 배열
랭크 0 : 스칼라(scalar)   7
    1 : 벡터(vector)    [10,10]
    2 : 행렬(matrix)    [[3,2],[1,2]]  
    3 : 3차원 텐서(3-order tensor)  [ [[3,2],[1,2]], [[3,2],[1,2]] ] 
    n : n차원 텐서(n-order tensor)  

In [4]:
# 넘파이를 이용한 배열생성(1차원)
test_array = np.array([1,4,5,8],float)

In [5]:
test_array

array([1., 4., 5., 8.])

In [6]:
#파이썬 리스트와 넘파이배열의 차이점?
test_list = [1,2,3]
np.array(test_list,int)

array([1, 2, 3])

In [11]:
test_list = [[1,4,5.5,8],[1,4.4,5,8]]
test_list

[[1, 4, 5.5, 8], [1, 4.4, 5, 8]]

In [12]:
np.array(test_list,int)

array([[1, 4, 5, 8],
       [1, 4, 5, 8]])

In [13]:
# 넘파일 배열은 데이터 개수가 동일
# 동일한 데이터 타입
# 검색이나 연산속도가 리스트보다 훨씬 빠름

In [14]:
test_ary = np.array([1,5,8,7],float)
test_ary

array([1., 5., 8., 7.])

In [15]:
test_ary[2]

8.0

In [16]:
type(test_ary[2])

numpy.float64

In [17]:
test_ary.dtype

dtype('float64')

In [18]:
test_ary.shape

(4,)

In [19]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix).shape

(3, 4)

In [23]:
np.array(matrix).ndim

2

In [20]:
tensor_rank3 = [
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
]
np.array(tensor_rank3,int).shape

(4, 3, 4)

In [21]:
np.array(tensor_rank3,int).ndim

3

In [25]:
np.array(tensor_rank3,dtype=int).size

48

In [28]:
import sys
np.array([[1,2,3.5],[4,5,6.5]], np.float64).itemsize

8

In [29]:
np.array([[1,2,3.5],[4,5,6.5]], np.float32).itemsize

4

In [31]:
x = np.array([[1,2,5,8],[1,2,5,8]])
x.shape

(2, 4)

In [34]:
x.reshape(8,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [36]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [37]:
list(range(8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [39]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [40]:
x.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
x.reshape(2,4).shape

(2, 4)

In [42]:
x.reshape(-1,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [43]:
x.reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [44]:
np.array(range(8)).reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [47]:
x = np.array(range(8)).reshape(-1,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [48]:
x.reshape(-1,)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [49]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [50]:
# [행][열],[행,열]

In [51]:
x = np.array(range(6),int).reshape(2,-1)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [54]:
x[1][1]

4

In [55]:
x[1,1]

4

In [56]:
x[1,1] = 100
x

array([[  0,   1,   2],
       [  3, 100,   5]])

In [57]:
list_a = list(range(10))
list_a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [58]:
list_a[:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [59]:
list_a[:2]

[0, 1]

In [60]:
x = np.array(range(16),int).reshape(4,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
x[:2, ] 

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [62]:
x[:2, : ] 

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [63]:
x[:2, :2] 

array([[0, 1],
       [4, 5]])

In [64]:
x[1:3 ,1:3 ]

array([[ 5,  6],
       [ 9, 10]])

In [65]:
x = np.array(range(15),int).reshape(3,-1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
x[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [67]:
x[::2 ,::3  ]

array([[ 0,  3],
       [10, 13]])

In [68]:
# arange 소수점 값을 주기적으로 생성할때 사용
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.arange(-5,5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [70]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [71]:
# 배열객체
# ones, zeros, empty

In [72]:
np.ones(shape=(5,2),dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [73]:
np.zeros(shape=(5,2),dtype=np.int8)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

In [75]:
np.empty(shape=(5,2),dtype=np.float32)

array([[2.4479718e+08, 5.6051939e-43],
       [0.0000000e+00, 4.5906538e-41],
       [1.2779842e-42, 0.0000000e+00],
       [1.0761972e-42, 5.6051939e-43],
       [0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [76]:
# ones_like, zeros_like, empty_like
# 기존 넘파이 배열과 같은 크기로 만들어서.. 내용을.... 채운다..

In [77]:
x = np.arange(12).reshape(3,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [79]:
# 단위행렬
# identity 
np.identity(n=3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [80]:
np.identity(n=10,dtype=int) # 정방향

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [82]:
# eye 시작점과 행렬 크기를 지정해서 단위행렬
# n: 행의 개수  M은 열의 개수 , k는 열의값을 기준으로 시작 인덱스
np.eye(N=3,M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [83]:
np.eye(N=3,M=5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [84]:
# diag 함수 행렬의 대각성분 값을 추출
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
np.diag(x)

array([0, 4, 8])

In [86]:
np.diag(x, k=1)

array([1, 5])

In [87]:
# uniform함수 : 균등분포 함수
# 시작값 끝값 데이터개수
np.random.uniform(0,5,10)

array([4.16921465, 0.47414812, 1.46745855, 4.27177577, 1.72253722,
       3.54811002, 0.51625437, 3.15068768, 4.16989206, 3.19480839])

In [88]:
# 정규분포
# 평균값, 분산, 데이터 개수
np.random.normal(0,2,10)

array([ 4.04679894,  0.55602056,  5.04558306, -1.84712657,  1.97317015,
        2.80213568,  0.21897062,  0.15400459, -0.56333389, -0.10283565])

In [89]:
# 넘파일 배열 연산
# 연산함수
# 축(axis)
# sum

In [90]:
test_array =  np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
test_array.sum()

55

In [92]:
test_array = np.arange(1,13).reshape(3,-1)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
test_array.shape

(3, 4)

In [93]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [95]:
test_array.sum(axis=1)

array([10, 26, 42])

In [96]:
test_array =  np.arange(1,13).reshape(3,4)
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [97]:
third_order_tensor.shape

(3, 3, 4)

In [98]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [99]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [100]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [101]:
third_order_tensor.mean(axis=0)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [102]:
third_order_tensor.mean(axis=1)

array([[5., 6., 7., 8.],
       [5., 6., 7., 8.],
       [5., 6., 7., 8.]])

In [103]:
third_order_tensor.mean(axis=2)

array([[ 2.5,  6.5, 10.5],
       [ 2.5,  6.5, 10.5],
       [ 2.5,  6.5, 10.5]])

In [104]:
# 표준편차 연산
third_order_tensor.std()

3.452052529534663

In [105]:
third_order_tensor.std(axis=0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
# 제곱근
np.sqrt(third_order_tensor)

array([[[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]],

       [[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]],

       [[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]]])

In [107]:
# 연결함수
# vstack 함수 : 배열을 수직으로 붙여서 하나의 행렬을 생성
# hstack 함수 : 배열을 수평으로 붙여서 하나의 행렬을 생성

In [108]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.vstack( (v1,v2) )

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
np.hstack( (v1,v2))

array([1, 2, 3, 4, 5, 6])

In [110]:
v1 = v1.reshape(-1,1)
v2 = v2.reshape(-1,1)
v1, v2

(array([[1],
        [2],
        [3]]),
 array([[4],
        [5],
        [6]]))

In [111]:
np.vstack((v1,v2 ) )

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [112]:
np.hstack((v1,v2 ) )

array([[1, 4],
       [2, 5],
       [3, 6]])

In [118]:
v1 = np.array([[1,2,3]])
v2 = np.array([[4,5,6]])
v1, v2

(array([[1, 2, 3]]), array([[4, 5, 6]]))

In [119]:
v1.shape, v2.shape

((1, 3), (1, 3))

In [122]:
np.concatenate( (v1,v2), axis=0  )

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
# concatenate 함수와 stack계열의 함수는
# concatenate 두개의 차원이 같아야함, 2차원 이상
# stack계열은 1차원도 가능
# 그래서 굳이 1차원의 데이터를 concatenate함수를 사용하려면 2차원 변경하고 사용

In [124]:
v1 = np.array([1,2,3,4]).reshape(2,2)
v1

array([[1, 2],
       [3, 4]])

In [126]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [134]:
v2 = np.array([[10,11]])
v2

array([[10, 11]])

In [135]:
v2.shape

(1, 2)

In [136]:
v2 = v2.T
v2

array([[10],
       [11]])

In [137]:
v1, v2

(array([[1, 2],
        [3, 4]]),
 array([[10],
        [11]]))

In [138]:
np.concatenate(( v1,v2),axis=1 )

array([[ 1,  2, 10],
       [ 3,  4, 11]])